### ISSUE TITLE
Проблемное судилище

### ISSUE THREAD

**Issue by danilasar** [InTeam-Russia/trash#21]
Необходимо реализовать путь жизни таски: создание, решение, верификация решения автором, народный арбитраж, закрытие

**Comment by ProstoLive** [comment]
![судилище](https://github.com/InTeam-Russia/trash/assets/52866075/8d1e17af-5e34-4944-9e3e-5ffd714768a7)

**Comment by ProstoLive** [comment]
Создание таски (/problems/create), решение (/problems/verificate, отправляется исполнителем в случае завершения), верификация решения автором (/problems/finish и /problems/voting) реализованы текущим функционалом продукта.

Народный арбитраж (/voting/vote/{problem_id}) и закрытие (/voting/delete_from_voting/{problem_id}) будут отправлены на пулл реквест как только будут устранены несостыковки с базой данных и другие мелкие проблемы, которые описал в телеграмме
